<?php
/**
 * @Author: cnzhihua
 * @Time: 18-2-4 16:05
 * @Github: https://github.com/Hzhihua
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '序号',
    'Content' => '评论内容',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => '父类 序号',
    'Status' => '状态',
    'Level' => 'Level',
    'Created by' => '创建于',
    'Updated by' => '更新于',
    'Related to' => 'Related to',
    'Url' => '文章地址',
    'Created date' => '创建新日期',
    'Updated date' => '更新日期',
    'View' => '查看',
    'Update' => '编辑',
    'Delete' => '删除',
    'Reply' => '回复',
    'Comments ({0})' => '评论 ({0})',
    'Comment cannot be blank.' => '评论不能为空.',
    'Comment has not been deleted. Please try again!' => '评论已经被删除。请稍后再试！',
    'Add a comment...' => '添加评论中...',
    'Comment' => '评论',
    'Oops, something went wrong. Please try again later.' => '抱歉，出现了未知错误，请稍后再试。',
    'The requested page does not exist.' => '请求的页面不存在，请稍后再试。',
    'Comment has been deleted.' => '评论已经被删除',
    'Comment has been saved.' => '评论已经被保存',
    'Click here to cancel reply.' => '点击这里取消回复。',
    'Comments Management' => '管理评论',
    'Select Status' => '请选择状态',
    'Select Author' => '请选择作者',
    'Update Comment: {0}' => '更新评论: {0}',
    'Active' => '激活',
    'Deleted' => '删除',
    'Go Back' => '返回',
];
